builds:
  -
    id: "lteinfo"
    binary: lteinfo
    main: ./cmd/lteinfo/main.go
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - freebsd
      - darwin
      - windows
    goarch:
      - amd64
      - arm
      - arm64
    goarm:
      - 7
archives:
  -
    id: lteinfo-binaries
    name_template: "lteinfo-{{ .Os }}_{{ .Arch }}_{{ .Version }}"
    files:
      - LICENSE.md
      - README.md
checksum:
  name_template: 'checksums.txt'
snapshot:
  name_template: "{{ .Tag }}-next"
changelog:
  sort: asc
  filters:
    exclude:
nfpms:
  -
    file_name_template: "lteinfo_package_{{ .Version }}_{{ .Os }}_{{ .Arch }}"
    vendor: Michael Paepcke
    homepage: https://paepcke.de/lteinfo
    maintainer: Michael Paepcke <git@paepcke.de>
    description: lteinfo
    license: BSD 3-Clause
    formats:
      - deb
      - rpm
